name: ATEnchants
author: xPrim69x
description: AT enchants by xPrim69x
version: 1.0.0
main: xPrim69x\ATEnchants\Main
api: [3.0.0]
mcpe-protocol: [408]
permissions:
  customenchant.command:
    default: op
    description: "Enchant items"
